### ISSUE TITLE
CLI downloaded all the packages... to my root

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/Sitefinity-CLI#301]
CLI downloaded the 15.1 

```
sf upgrade McMasterOptimalAging.sln
```

...this ruins the rest of my morning
![image](https://github.com/user-attachments/assets/0afa6ee5-dc31-42a0-8eea-2ae17bac4a64)

**Comment by RuzmanovDev** [comment]
HI, @sitefinitysteve. 

Sorry to hear that you are having issues with the CLI. I will log that issue in our backlog so we can take a look at it and fix it. In the meantime there is a workaround that I can suggest. You can pass the full path to the  .sln file. If you do so you won't have packages downloaded in the wrong folder.

Best,
Stoyan

**Comment by RuzmanovDev** [comment]
The issue is fixed in the latest release https://github.com/Sitefinity/Sitefinity-CLI/releases/tag/v1.1.0.49
