### ISSUE TITLE
Upgrade doesn't work for projects with no packages.config file

### ISSUE THREAD

**Issue by gchokov** [Sitefinity/Sitefinity-CLI#58]
info      [C:\Projects\xxx\xxxx] Install for package "Telerik.Sitefinity.All" is complete
info      Exporting powershell config...
info      Detected sitefinity version for "C:\Projects\xxx\xxx\SitefinityWebApp.csproj" - "4.0.790.0"
info      Collecting Sitefinity NuGet package tree for "C:\Projects\xxx\xxx\SitefinityWebApp.csproj"...
info      Start processing HTTP request GET http://nuget.sitefinity.com/nuget//Packages(Id='Telerik.Sitefinity.All',Version='4.0.790.0')
info      Sending HTTP request GET http://nuget.sitefinity.com/nuget//Packages(Id='Telerik.Sitefinity.All',Version='4.0.790.0')
info      Received HTTP response after 1102.1852ms - NotFound
info      End processing HTTP request after 1108.6487ms - NotFound
fail      File "packages.config" not found in project directory "C:\Projects\wxxx\xxx". Cannot proceed with upgrade.

**Comment by RuzmanovDev** [comment]
Yes, currently the upgrade commands supports upgrades only if you have Sitefinity installation with nugets
