### ISSUE TITLE
Execution policy blocks running of updater.ps1 file

### ISSUE THREAD

**Issue by JoshuaDouce** [Sitefinity/Sitefinity-CLI#67]
In order to get the updater to run I had to run this command first

Unblock-File -Path '.\PowerShell\Updater.ps1'

**Comment by RuzmanovDev** [comment]
Thanks for the feedback, We will add it to our backlog. Expect fix in future versions of the CLI

**Comment by azavarben** [comment]
Same issue.

**Comment by RuzmanovDev** [comment]
The issue is fixed in https://github.com/Sitefinity/Sitefinity-CLI/releases/tag/v1.1.0.18
