### ISSUE TITLE
Update Contribution Readme with instructions on how to setup the project

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/Sitefinity-CLI#7]
Pulling it down and building 👍  But about 7 of the tests fail OOTB

Is this just an old version, or...?

![image](https://user-images.githubusercontent.com/1542376/40844907-251ee144-6583-11e8-8fdb-f5fa90983f80.png)

**Comment by Novkirishki** [comment]
Tests are fixed :)
