### ISSUE TITLE
sf upgrade: fail - Unable to find package 'Telerik.Sitefinity.All

### ISSUE THREAD

**Issue by kreediam** [Sitefinity/Sitefinity-CLI#95]
I noticed that if my solution file name has a space in it (example: "Solution Name"), I get an error that says, "fail - Unable to find package 'Telerik.Sitefinity.All' at source 'Solution'. Source not found." It seems to be using the first word of the solution title as a package source in this case.

**Comment by RuzmanovDev** [comment]
Thanks for reporting this issue. It's in our backlog and will be fixed in future versions of the CLI

**Comment by RuzmanovDev** [comment]
The issue is fixed in https://github.com/Sitefinity/Sitefinity-CLI/releases/tag/v1.1.0.18
